language: node_js
node_js:
  - "5"
  - "4.2"
  - "4"
  - "0.12"
before_install:
  - npm install coveralls
  - npm install mocha-lcov-reporter
script: npm run-script coveralls
branches:
  only:
    - master
